import type { CommercialFacilityType } from "../db/types.js";
import {
  canonicalizeLocale,
  type SupportedLocale,
} from "./supported-locales.js";

export const commercialTemplateActivityKeys = {
  traditional_gym: ["openGym", "guidedClass"],
  crossfit: ["wod", "openBox"],
  hyrox: ["hyrox", "stationTechnique"],
  functional_training: ["functionalTraining"],
  personal_training: ["individualSession"],
  powerlifting: ["strength", "technique"],
  strongman: ["strongman"],
  bodybuilding: ["bodybuildingRoom"],
  martial_arts: ["technique", "sparring"],
  yoga: ["yoga"],
  pilates: ["pilates"],
  indoor_cycling: ["indoorCycling"],
  multidisciplinary: ["guidedActivity", "openTraining"],
  custom: ["customActivity"],
} as const satisfies Record<CommercialFacilityType, readonly string[]>;

export type CommercialTemplateActivityKey =
  (typeof commercialTemplateActivityKeys)[CommercialFacilityType][number];

export const completeCommercialTemplateLocales = [
  "es",
  "en",
  "de",
  "fr",
  "it",
  "gl",
  "ca",
  "eu",
  "oc-aranes",
] as const;

type CompleteTemplateLocale =
  (typeof completeCommercialTemplateLocales)[number];

export const commercialTemplateActivityLabels = {
  es: {
    openGym: "Sala libre",
    guidedClass: "Clase dirigida",
    wod: "WOD",
    openBox: "Open Box",
    hyrox: "HYROX",
    stationTechnique: "Técnica de estaciones",
    functionalTraining: "Entrenamiento funcional",
    individualSession: "Sesión individual",
    strength: "Fuerza",
    technique: "Técnica",
    strongman: "Strongman",
    bodybuildingRoom: "Sala de musculación",
    sparring: "Sparring",
    yoga: "Yoga",
    pilates: "Pilates",
    indoorCycling: "Ciclo indoor",
    guidedActivity: "Actividad dirigida",
    openTraining: "Entrenamiento libre",
    customActivity: "Actividad personalizada",
  },
  en: {
    openGym: "Open gym",
    guidedClass: "Instructor-led class",
    wod: "WOD",
    openBox: "Open Box",
    hyrox: "HYROX",
    stationTechnique: "Station technique",
    functionalTraining: "Functional training",
    individualSession: "Individual session",
    strength: "Strength",
    technique: "Technique",
    strongman: "Strongman",
    bodybuildingRoom: "Weight room",
    sparring: "Sparring",
    yoga: "Yoga",
    pilates: "Pilates",
    indoorCycling: "Indoor cycling",
    guidedActivity: "Instructor-led activity",
    openTraining: "Open training",
    customActivity: "Custom activity",
  },
  de: {
    openGym: "Freier Trainingsbereich",
    guidedClass: "Angeleiteter Kurs",
    wod: "WOD",
    openBox: "Open Box",
    hyrox: "HYROX",
    stationTechnique: "Stationstechnik",
    functionalTraining: "Funktionelles Training",
    individualSession: "Einzeltraining",
    strength: "Kraft",
    technique: "Technik",
    strongman: "Strongman",
    bodybuildingRoom: "Kraftraum",
    sparring: "Sparring",
    yoga: "Yoga",
    pilates: "Pilates",
    indoorCycling: "Indoor Cycling",
    guidedActivity: "Angeleitete Aktivität",
    openTraining: "Freies Training",
    customActivity: "Benutzerdefinierte Aktivität",
  },
  fr: {
    openGym: "Accès libre à la salle",
    guidedClass: "Cours encadré",
    wod: "WOD",
    openBox: "Open Box",
    hyrox: "HYROX",
    stationTechnique: "Technique des stations",
    functionalTraining: "Entraînement fonctionnel",
    individualSession: "Séance individuelle",
    strength: "Force",
    technique: "Technique",
    strongman: "Strongman",
    bodybuildingRoom: "Salle de musculation",
    sparring: "Sparring",
    yoga: "Yoga",
    pilates: "Pilates",
    indoorCycling: "Cyclisme en salle",
    guidedActivity: "Activité encadrée",
    openTraining: "Entraînement libre",
    customActivity: "Activité personnalisée",
  },
  it: {
    openGym: "Accesso libero alla palestra",
    guidedClass: "Corso guidato",
    wod: "WOD",
    openBox: "Open Box",
    hyrox: "HYROX",
    stationTechnique: "Tecnica delle stazioni",
    functionalTraining: "Allenamento funzionale",
    individualSession: "Sessione individuale",
    strength: "Forza",
    technique: "Tecnica",
    strongman: "Strongman",
    bodybuildingRoom: "Sala pesi",
    sparring: "Sparring",
    yoga: "Yoga",
    pilates: "Pilates",
    indoorCycling: "Ciclismo indoor",
    guidedActivity: "Attività guidata",
    openTraining: "Allenamento libero",
    customActivity: "Attività personalizzata",
  },
  gl: {
    openGym: "Acceso libre ao ximnasio",
    guidedClass: "Clase dirixida",
    wod: "WOD",
    openBox: "Box aberto",
    hyrox: "HYROX",
    stationTechnique: "Técnica de estacións",
    functionalTraining: "Adestramento funcional",
    individualSession: "Sesión individual",
    strength: "Forza",
    technique: "Técnica",
    strongman: "Strongman",
    bodybuildingRoom: "Sala de musculación",
    sparring: "Combate de adestramento",
    yoga: "Ioga",
    pilates: "Pilates",
    indoorCycling: "Ciclismo en interior",
    guidedActivity: "Actividade dirixida",
    openTraining: "Adestramento libre",
    customActivity: "Actividade personalizada",
  },
  ca: {
    openGym: "Accés lliure al gimnàs",
    guidedClass: "Classe dirigida",
    wod: "WOD",
    openBox: "Box obert",
    hyrox: "HYROX",
    stationTechnique: "Tècnica d’estacions",
    functionalTraining: "Entrenament funcional",
    individualSession: "Sessió individual",
    strength: "Força",
    technique: "Tècnica",
    strongman: "Strongman",
    bodybuildingRoom: "Sala de musculació",
    sparring: "Combat d’entrenament",
    yoga: "Ioga",
    pilates: "Pilates",
    indoorCycling: "Ciclisme d’interior",
    guidedActivity: "Activitat dirigida",
    openTraining: "Entrenament lliure",
    customActivity: "Activitat personalitzada",
  },
  eu: {
    openGym: "Gimnasio irekia",
    guidedClass: "Eskola gidatua",
    wod: "WOD",
    openBox: "Box irekia",
    hyrox: "HYROX",
    stationTechnique: "Estazioetako teknika",
    functionalTraining: "Entrenamendu funtzionala",
    individualSession: "Banakako saioa",
    strength: "Indarra",
    technique: "Teknika",
    strongman: "Strongman",
    bodybuildingRoom: "Kulturismo-aretoa",
    sparring: "Sparring",
    yoga: "Yoga",
    pilates: "Pilates",
    indoorCycling: "Barruko txirrindularitza",
    guidedActivity: "Jarduera gidatua",
    openTraining: "Entrenamendu librea",
    customActivity: "Jarduera pertsonalizatua",
  },
  "oc-aranes": {
    openGym: "Accès liure ath gimnàs",
    guidedClass: "Classa dirigida",
    wod: "WOD",
    openBox: "Accès liure ar espaci d’entrenament",
    hyrox: "HYROX",
    stationTechnique: "Tecnica des estacions",
    functionalTraining: "Entrenament foncionau",
    individualSession: "Session individuau",
    strength: "Fòrça",
    technique: "Tecnica",
    strongman: "Strongman",
    bodybuildingRoom: "Sala de musculacion",
    sparring: "Combat d’entrenament",
    yoga: "Iòga",
    pilates: "Pilates",
    indoorCycling: "Ciclisme interior",
    guidedActivity: "Activitat dirigida",
    openTraining: "Entrenament liure",
    customActivity: "Activitat personalizada",
  },
} as const satisfies Record<
  CompleteTemplateLocale,
  Record<CommercialTemplateActivityKey, string>
>;

function completeTemplateLocale(
  locale: SupportedLocale,
): CompleteTemplateLocale {
  if (locale === "de-CH") return "de";
  if (locale === "ca-valencia") return "ca";
  return locale;
}

export function localizedCommercialTemplateClassTypes(
  facilityType: CommercialFacilityType,
  requestedLocale: unknown,
): string[] {
  const locale = completeTemplateLocale(canonicalizeLocale(requestedLocale));
  const labels = commercialTemplateActivityLabels[locale];
  return commercialTemplateActivityKeys[facilityType].map((key) => labels[key]);
}
